# Generated by Django 4.0.4 on 2022-05-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
